export const Env = {
  EMAILJS_PUBLIC_KEY: process.env.NEXT_PUBLIC_EMAILJS_PUBLIC_KEY,
  EMAILJS_SUBSCRIBE_SERVICE_ID: process.env.NEXT_PUBLIC_EMAILJS_SUBSCRIBE_SERVICE_ID,
  EMAILJS_SUBSCRIBE_TEMPLATE_ID: process.env.NEXT_PUBLIC_EMAILJS_SUBSCRIBE_TEMPLATE_ID,
};
