import type { Metadata } from 'next';
import { NextIntlClientProvider } from 'next-intl';
import { getMessages } from 'next-intl/server';
import { FC } from 'react';

import { RootLayoutPropsType } from '@app/[locale]/type';
import { Footer } from '@components/Footer';
import { Header } from '@components/Header';
import { inter } from '@styles/fonts';

import '@styles/globals.scss';

export const metadata: Metadata = {
  title: 'Client Blog',
  description: 'Generated by create next app',
};

const RootLayout: FC<RootLayoutPropsType> = async ({ children, params: { locale } }) => {
  const messages = await getMessages();

  return (
    <html lang={locale} className={inter.className}>
      <body>
        <NextIntlClientProvider locale={locale} messages={messages}>
          <div id="root">
            <Header />
            <main>{children}</main>
            <Footer />
          </div>
        </NextIntlClientProvider>
      </body>
    </html>
  );
};

export default RootLayout;
